name: Deploy on Master

on:
  push:
    branches:
      - master

    jobs:
      deploy:
        name: Deploy
        runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        - name: Deploy to staging server
          uses: easingthemes/ssh-deploy@v2.0.7
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}









jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create Artifact Directory
      run: mkdir -p artifacts/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        stock_api_key: ${{ secrets.stock_api_key }}
      run: |
        pip install pytest
        pytest tests/
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: test-artifact
        path: artifacts/